;this file for FamiTone2 library generated by text2data tool

plodding_music_data:
	.byte 1
	.word @instruments
	.word @samples-3
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,307,256 ; New song

@instruments:
	.byte $b0 ;instrument $00
	.word @env1,@env0,@env0
	.byte $00
	.byte $f0 ;instrument $01
	.word @env2,@env0,@env0
	.byte $00
	.byte $30 ;instrument $02
	.word @env3,@env0,@env0
	.byte $00

@samples:
@env0:
	.byte $c0,$00,$00
@env1:
	.byte $c8,$c3,$c0,$c6,$c2,$c0,$00,$05
@env2:
	.byte $c5,$c4,$c3,$c2,$c2,$c1,$c0,$00,$06
@env3:
	.byte $c8,$c4,$c1,$c0,$c6,$c4,$c3,$c0,$00,$07


; New song
@song0ch0:
	.byte $fb,$05
@song0ch0loop:
@ref0:
	.byte $80,$32,$8d,$3a,$8d,$40,$95,$3c,$85,$3a,$95,$3a,$85,$3a,$85,$44
	.byte $85,$44,$8d
@ref1:
	.byte $32,$8d,$3a,$8d,$40,$95,$3c,$85,$3a,$95,$3a,$85,$3a,$85,$44,$85
	.byte $44,$8d
@ref2:
	.byte $5c,$85,$59,$5c,$91,$4d,$53,$63,$58,$91,$52,$8d,$4e,$8d,$4b,$4a
	.byte $91,$52,$85
	.byte $ff,$13
	.word @ref2
	.byte $fd
	.word @song0ch0loop

; New song
@song0ch1:
@song0ch1loop:
@ref4:
	.byte $f9,$85
@ref5:
	.byte $f9,$85
@ref6:
	.byte $f9,$85
@ref7:
	.byte $f9,$85
	.byte $fd
	.word @song0ch1loop

; New song
@song0ch2:
@song0ch2loop:
@ref8:
	.byte $84,$2c,$99,$23,$2c,$99,$23,$2c,$99,$23,$2c,$99,$22,$81
@ref9:
	.byte $2c,$99,$23,$2c,$99,$23,$2c,$99,$23,$2c,$99,$22,$81
	.byte $ff,$0d
	.word @ref9
	.byte $ff,$0d
	.word @ref9
	.byte $fd
	.word @song0ch2loop

; New song
@song0ch3:
@song0ch3loop:
@ref12:
	.byte $82,$20,$8d,$20,$8d,$20,$8d,$20,$8d,$20,$8d,$20,$8d,$20,$8d,$20
	.byte $8d
@ref13:
	.byte $20,$8d,$20,$8d,$20,$8d,$20,$8d,$20,$8d,$20,$8d,$20,$8d,$20,$8d
	.byte $ff,$10
	.word @ref13
	.byte $ff,$10
	.word @ref13
	.byte $fd
	.word @song0ch3loop

; New song
@song0ch4:
@song0ch4loop:
@ref16:
	.byte $f9,$85
@ref17:
	.byte $f9,$85
@ref18:
	.byte $f9,$85
@ref19:
	.byte $f9,$85
	.byte $fd
	.word @song0ch4loop
