;this file for FamiTone2 library generated by text2data tool

musicfinalmaybe_music_data:
	.byte 4
	.word @instruments
	.word @samples-3
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,307,256 ; inside
	.word @song1ch0,@song1ch1,@song1ch2,@song1ch3,@song1ch4,307,256 ; title
	.word @song2ch0,@song2ch1,@song2ch2,@song2ch3,@song2ch4,307,256 ; outside
	.word @song3ch0,@song3ch1,@song3ch2,@song3ch3,@song3ch4,307,256 ; king

@instruments:
	.byte $b0 ;instrument $00
	.word @env1,@env0,@env0
	.byte $00
	.byte $f0 ;instrument $01
	.word @env2,@env0,@env0
	.byte $00
	.byte $30 ;instrument $02
	.word @env3,@env0,@env0
	.byte $00
	.byte $70 ;instrument $03
	.word @env4,@env0,@env0
	.byte $00

@samples:
@env0:
	.byte $c0,$00,$00
@env1:
	.byte $c8,$c3,$c0,$c8,$c3,$c0,$00,$05
@env2:
	.byte $c5,$c4,$c3,$c2,$c2,$c1,$c0,$00,$06
@env3:
	.byte $c8,$c4,$c1,$c0,$c6,$c4,$c3,$c0,$00,$07
@env4:
	.byte $c9,$00,$00


; inside
@song0ch0:
	.byte $fb,$05
@song0ch0loop:
@ref0:
	.byte $80,$32,$8d,$3a,$8d,$40,$95,$3c,$85,$3a,$95,$3a,$85,$3a,$85,$44
	.byte $85,$44,$8d
@ref1:
	.byte $32,$8d,$3a,$8d,$40,$95,$3c,$85,$3a,$95,$3a,$85,$3a,$85,$44,$85
	.byte $44,$8d
@ref2:
	.byte $5c,$85,$59,$5c,$91,$4d,$53,$63,$58,$91,$52,$8d,$4e,$8d,$4b,$4a
	.byte $91,$52,$85
	.byte $ff,$13
	.word @ref2
	.byte $fd
	.word @song0ch0loop

; inside
@song0ch1:
@song0ch1loop:
@ref4:
	.byte $f9,$85
@ref5:
	.byte $f9,$85
@ref6:
	.byte $f9,$85
@ref7:
	.byte $f9,$85
	.byte $fd
	.word @song0ch1loop

; inside
@song0ch2:
@song0ch2loop:
@ref8:
	.byte $84,$2c,$99,$23,$2c,$99,$23,$2c,$99,$23,$2c,$99,$22,$81
@ref9:
	.byte $2c,$99,$23,$2c,$99,$23,$2c,$99,$23,$2c,$99,$22,$81
	.byte $ff,$0d
	.word @ref9
	.byte $ff,$0d
	.word @ref9
	.byte $fd
	.word @song0ch2loop

; inside
@song0ch3:
@song0ch3loop:
@ref12:
	.byte $82,$20,$8d,$20,$8d,$20,$8d,$20,$8d,$20,$8d,$20,$8d,$20,$8d,$20
	.byte $8d
@ref13:
	.byte $20,$8d,$20,$8d,$20,$8d,$20,$8d,$20,$8d,$20,$8d,$20,$8d,$20,$8d
	.byte $ff,$10
	.word @ref13
	.byte $ff,$10
	.word @ref13
	.byte $fd
	.word @song0ch3loop

; inside
@song0ch4:
@song0ch4loop:
@ref16:
	.byte $f9,$85
@ref17:
	.byte $f9,$85
@ref18:
	.byte $f9,$85
@ref19:
	.byte $f9,$85
	.byte $fd
	.word @song0ch4loop


; title
@song1ch0:
	.byte $fb,$08
@song1ch0loop:
@ref20:
	.byte $86,$40,$3e,$3c,$3a,$38,$36,$34,$3a,$33,$00,$85,$3a,$81
@ref21:
	.byte $3d,$01,$37,$01,$33,$00,$89
@ref22:
	.byte $8f,$33,$00,$85,$3a,$81
	.byte $ff,$07
	.word @ref21
	.byte $fd
	.word @song1ch0loop

; title
@song1ch1:
@song1ch1loop:
@ref24:
	.byte $00,$9d
@ref25:
	.byte $9b,$86,$32,$81
@ref26:
	.byte $41,$3d,$3b,$3d,$00,$8d
@ref27:
	.byte $8f,$3c,$40,$3c,$40,$3c,$40,$3c,$40
	.byte $fd
	.word @song1ch1loop

; title
@song1ch2:
@song1ch2loop:
@ref28:
	.byte $80,$32,$85,$40,$85,$32,$85,$40,$85
@ref29:
	.byte $32,$85,$40,$85,$32,$85,$40,$85
	.byte $ff,$08
	.word @ref29
	.byte $ff,$08
	.word @ref29
	.byte $fd
	.word @song1ch2loop

; title
@song1ch3:
@song1ch3loop:
@ref32:
	.byte $86,$20,$00,$20,$00,$20,$00,$20,$00,$20,$00,$83,$08,$00,$83
@ref33:
	.byte $20,$00,$83,$08,$00,$83,$20,$00,$83,$08,$00,$83
	.byte $ff,$0c
	.word @ref33
	.byte $ff,$0c
	.word @ref33
	.byte $fd
	.word @song1ch3loop

; title
@song1ch4:
@song1ch4loop:
@ref36:
	.byte $9f
@ref37:
	.byte $9f
@ref38:
	.byte $9f
@ref39:
	.byte $9f
	.byte $fd
	.word @song1ch4loop


; outside
@song2ch0:
	.byte $fb,$06
@song2ch0loop:
@ref40:
	.byte $f9,$85
	.byte $fd
	.word @song2ch0loop

; outside
@song2ch1:
@song2ch1loop:
@ref41:
	.byte $f9,$85
	.byte $fd
	.word @song2ch1loop

; outside
@song2ch2:
@song2ch2loop:
@ref42:
	.byte $f9,$85
	.byte $fd
	.word @song2ch2loop

; outside
@song2ch3:
@song2ch3loop:
@ref43:
	.byte $f9,$85
	.byte $fd
	.word @song2ch3loop

; outside
@song2ch4:
@song2ch4loop:
@ref44:
	.byte $f9,$85
	.byte $fd
	.word @song2ch4loop


; king
@song3ch0:
	.byte $fb,$09
@song3ch0loop:
@ref45:
	.byte $82,$33,$37,$39,$3d,$41,$39,$41,$01,$3f,$37,$3f,$01,$3d,$35,$3d
	.byte $01,$33,$37,$39,$3d,$41,$39,$41,$4b,$47,$41,$39,$41,$46,$89,$46
	.byte $46
	.byte $fd
	.word @song3ch0loop

; king
@song3ch1:
@song3ch1loop:
@ref46:
	.byte $f9,$85
	.byte $fd
	.word @song3ch1loop

; king
@song3ch2:
@song3ch2loop:
@ref47:
	.byte $86,$33,$37,$39,$3d,$41,$39,$40,$42,$01,$3f,$37,$3e,$40,$01,$3d
	.byte $35,$3c,$3e,$01,$33,$37,$39,$3d,$41,$39,$41,$4a,$4c,$46,$48,$40
	.byte $42,$39,$41,$46,$83,$40,$46,$40,$46,$40
	.byte $fd
	.word @song3ch2loop

; king
@song3ch3:
@song3ch3loop:
	.byte $ff,$10
	.word @ref12
	.byte $fd
	.word @song3ch3loop

; king
@song3ch4:
@song3ch4loop:
@ref49:
	.byte $f9,$85
	.byte $fd
	.word @song3ch4loop
